# Generated by Django 4.2.1 on 2023-05-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=20)),
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('RFID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('RFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid_app.student')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid_app.room')),
            ],
        ),
    ]
