# Generated by Django 3.2.6 on 2023-05-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-time_in']},
        ),
    ]
